### ISSUE TITLE
NOT_FOUND error when trying access main webpage

### ISSUE THREAD

**Issue by adriengonz** [louis-genestier/fitnesspark-qrcode-generator#1]
Bonjour,
J'ai essayé d'héberger votre projet, mais quand je le démarre et que j'accede au localhost:3000, je tombe sur une page avec l'erreur NOT_FOUND.
<img width="1552" alt="Capture d’écran 2024-01-23 à 12 16 54" src="https://github.com/louis-genestier/fitnesspark-qrcode-generator/assets/40824310/805fd387-b62b-49f3-9a90-d01b5aff1f5b">

J'aurais également d'autres questions;
Comment récupérez vous l'ID et le number du compte ? J'ai essayé de comprendre votre code mais je ne vois a aucun moment des requêtes vers l'API fitness park.
Après avoir analysé mon QR code personnel pour l'accès a la salle, j'ai compris la manière dont vous voulez générer un QR Code, mais encore une fois, les valeurs changent selon l'heure de la journée, donc comment récupérer ces fameuses valeurs auprès de Fitness Park pour les intégrer dans le QR Code ?

Merci d'avance,

Adrien

**Comment by louis-genestier** [comment]
Hello,
Effectivement je n'ai pas encore mis en place la doc, je n'ai pas pris le temps de le faire 😅 
Sinon le fonctionnement est plutot simple:

- 1 endpoint pour générer le qrcode: `/qrcode/:id/:number`
- 1 endpoint pour afficher le qrcode: `/image/:id/:number`

Pour avoir ton `id` et ton `number` tu vas devoir te connecter sur ce site https://member.fr.fitnesspark.app/ avec les memes identifiants que sur l'application, et en ouvrant la partie network du devtool de ton navigateur tu devrais avoir une requete vers `https://api.fr.fitnesspark.app/fitnesspark/identificators`. Dans la réponse tu auras un objet `hydra:member`, qui contient l'id sous format `\/fitnesspark\/identificators\/1111111` (seul la dernière partie nous intéresse) et le number.

N'hésite pas si tu as un souci 😉

**Comment by adriengonz** [comment]
Salut,
Parfait merci d'avoir répondu aussi rapidement !
Je viens de regarder et ça a marché ! Je ne connaissais pas du tout cet api, au depart j'ai loggé toutes les requêtes de l'app Fitness Park quand je me connectais, je faisais de même avec le site et je trouvais rien d'intéressant, mais effectivement avec cet API j'ai toutes les infos nécessaires.
Merci encore pour ta réponse et pour ton projet qui est super intéressant également 😃 je cherchais ça car je paie un abonnement avec un ami et on peut pas être connecté tous les 2 sur l'app en même temps donc ton projet est super utile dans ce cas là
